# Generated by Django 5.0.2 on 2024-02-22 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AREA', to='core.district')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countofrooms', models.CharField(max_length=100, verbose_name='Количество комнат')),
                ('repair', models.TextField(verbose_name='Ремон')),
                ('furniture', models.CharField(max_length=50)),
                ('square', models.IntegerField(verbose_name='Площадь квартиры')),
                ('floors', models.IntegerField(verbose_name='Количество этажей')),
                ('wallmaterial', models.IntegerField(verbose_name='материал стен')),
                ('heating', models.CharField(max_length=30, verbose_name='Отопление')),
                ('yearofconstraction', models.IntegerField(verbose_name='Год постройки')),
                ('additionally', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=200)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='core.district')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20, verbose_name='Валюта')),
                ('mbank', models.CharField(max_length=20, verbose_name='МБанк')),
                ('company', models.CharField(max_length=200)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.rooms', verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Компания')),
                ('history', models.TextField(verbose_name='История компании')),
                ('descriptions', models.CharField(max_length=200)),
                ('portfolio', models.CharField(max_length=150)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='core.price', verbose_name='Имя')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='core.rooms', verbose_name='Имя')),
            ],
        ),
    ]
