# Generated by Django 5.0.2 on 2024-02-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='wallmaterial',
            field=models.CharField(max_length=30, verbose_name='материал стен'),
        ),
    ]
