# Generated by Django 5.0.2 on 2024-02-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rooms_name_alter_rooms_wallmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
