# Generated by Django 5.0.2 on 2024-02-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_price_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': 'Маркет', 'verbose_name_plural': 'Маркеты'},
        ),
        migrations.AlterField(
            model_name='rooms',
            name='yearofconstraction',
            field=models.DateTimeField(verbose_name='Год постройки'),
        ),
    ]
