# Generated by Django 5.0.2 on 2024-02-26 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_rooms_yearofconstraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='price',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rooms',
        ),
    ]
